# Exercícios Numpy

In [2]:
import numpy as np

---

In [ ]:
a=np.array([0]*10) #array filled with zeros
print(a)

[0 0 0 0 0 0 0 0 0 0]


In [3]:
b=np.arange(10, 20) #array from 10 to 20
print(b)

[10 11 12 13 14 15 16 17 18 19]


In [8]:
np.ones([2, 2], dtype=np.int32)
#print(a)

array([[1, 1],
       [1, 1]], dtype=int32)

In [ ]:
y=np.arange(4, dtype=np.int32)
print(y)
x=np.arange(4, dtype=np.int32)
np.ones_like(x) #transforma em valores [ 1 ]

[0 1 2 3]


array([1, 1, 1, 1], dtype=int32)