### Titulo

In [1]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import sys
import numpy as np

Basic Numpy arrays

In [3]:
np.array([1, 2, 3, 4])
a=np.array([1, 2, 3, 4])
b=np.array([0, 1, 1.5, 3])
a[1], b[2]

(np.int64(2), np.float64(1.5))

In [12]:
print(a[1], b[2])

2 1.5


In [10]:
print(a[1:])

[2 3 4]


In [11]:
print(a[1:-1])

[2 3]


In [14]:
print(a[::2])

[1 3]


In [18]:
print(a[0], a[2], a[3])
print(a[[0, 2, 3]])

1 3 4
[1 3 4]


---

In [5]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [9]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

---

## Dimenções - matrizes

In [2]:
o=np.array([
    [1, 2, 3],
    [4, 5, 6]
    ])

NameError: name 'np' is not defined

In [ ]:
print(type(o))
print(o.shape)
print(o.ndim)
print(o.size)

<class 'numpy.ndarray'>
(2, 3)
2
6


---

### Resumo Estatística

In [23]:
a = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]
             ])
print(f'Somar tudo: {a.sum()}')
print(f'Soma de toda a coluna (0 = vertical): {a.sum(axis=0)}')
print(f'Soma de toda a linha (1 = horizontal): {a.sum(axis=1)}')
print(f'Média: {a.mean()}')
print(f'Média de toda a linha: {a.mean(axis=1)}')
print(f'Desvio padrão: {a.std()}')

Somar tudo: 45
Soma de toda a coluna (0 = vertical): [12 15 18]
Soma de toda a linha (1 = horizontal): [ 6 15 24]
Média: 5.0
Média de toda a linha: [2. 5. 8.]
Desvio padrão: 2.581988897471611


---

### Operações vetorizadas

In [ ]:
a=np.arange(4) #gera uma sequencia do 0 - 3
print(a)
print(a+10) #adicionando +10 em todos os elementos
a+=100 #não pode ser adicionado dentro de uma função
print(f'+100: {a}')

#------
b=np.arange(4)
c=np.array([10, 10, 10, 10])
print(f'Soma B+C: {b+c}')

[0 1 2 3]
[10 11 12 13]
+100: [100 101 102 103]
Soma B+C: [10 11 12 13]


array([10, 11, 12, 13])

---

### Boolean Arrays

In [18]:
d=np.arange(4)
print(f'D -> {d}')
print(f'd[[0, -1]] -> {d[[0, -1]]}') #1° forma de exibir valores
print(f'd[[True, False, False, True]] -> {d[[True, False, False, True]]}') #2° forma de exibir valores
print(f'd>2 -> {d>2}')

D -> [0 1 2 3]
d[[0, -1]] -> [0 3]
d[[True, False, False, True]] -> [0 3]
d>2 -> [False False False  True]


In [19]:
a=np.arange(5)
print(f'A -> {a}')
print(f'a>=2 -> {a>=2}')
print(f'a[a >= 2] -> {a[a >= 2]}')

A -> [0 1 2 3 4]
a>=2 -> [False False  True  True  True]
a[a >= 2] -> [2 3 4]


In [24]:
a=np.arange(5)
a2=a.mean()
print(f'A -> {a}')
print(f'Mean A -> {a2}')
print(f'a>=a2 -> {a>=a2}')
print(f'a[a >= a2] -> {a[a >= a2]}')

A -> [0 1 2 3 4]
Mean A -> 2.0
a>=a2 -> [False False  True  True  True]
a[a >= a2] -> [2 3 4]


In [29]:
a=np.arange(5)
print(f'A -> {a}')
print(f'a[(a == 1) | (a==2) ] -> {a[(a == 1) | (a==2)]}')
print(f'a[(a<=2) & (a%2==0)] -> {a[(a <= 2) & (a%2==0)]}')

A -> [0 1 2 3 4]
a[(a == 1) | (a==2) ] -> [1 2]
a[(a<=2) & (a%2==0)] -> [0 2]


In [ ]:
b=np.random.randint(10, size=(2, 2))
print(f'B -> {b}')
print(f'b < 5 -> {b < 5}' )
mask=b[np.array([
    [True, False],
    [True, False]
    ])]
print(f'b[np.array([[True, False], [True, False]])] -> {mask}')

B -> [[5 5]
 [3 9]]
b < 5 -> [[False False]
 [ True False]]
b[np.array([[True, False], [True, False]])] -> [5 3]
